# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Skripsi/Nexys-A7-100T-Master.xdc

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: d:/Tugas/Skripsi/SourceCode/SHA-3/SHA-3.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
